project:
  type: website

website:
  favicon: "img/logo.png"
  title: "Formation continue (11.03)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - programme.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

margin-header: |
  ![](img/hepvs.png)

