project:
  type: website

website:
  page-footer: "2022 - Un projet de l'équipe Emotions - Bien-être - Apprentissages de la HEP-VS" 
  favicon: "img/logo.png"
  title: "Formation continue (11.03)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - programme.qmd
      - ressources.qmd
      - recherche.qmd
      - about.qmd

format:
  html:
    theme: 
    - cosmo
    - custom.scss

    css: styles.css
    toc: false

editor: source

margin-header: |
  ![](img/hepvs.png)

