---
title: "Programme général de la formation"
toc: true
toc-title: "Parcourir la description"
---


## Rencontre du jeudi 11 août 2022 de 14h30 à 16h30

*Salle : 220, bâtiment principal de la HEP-VS, site de St-Maurice, Rez-de-chaussée*

- Accueil
- Présentation de l'organisation
- Présentation des forces de caractères
- Expérimentations

Proposition d'activités avant la prochaine séance : 

- Réaliser le test VIA des forces
- Noter son top 5 des forces
- Observer leur utilisation
- Approfondir sa propre compréhension des enjeux

## Rencontre du jeudi 25 août 2022 de 17h30 à 19h10

*Salle : info à venir*

- Présentation de la séquence clé-en-main
- Utilisation de la séquence clé-en-main

Proposition d'activités avant la prochaine séance : 

- Utilisation du matériel avec ses élèves
- Participation à la recherche (*facultatif et sur inscription*)

## Rencontre du jeudi 6 octobre 2022 de 17h30 à 19h10

*Salle : info à venir*

- Echange de pratiques sur les premières expériences avec les élèves
- Approfondissement d'activités pédagogiques

Proposition d'activités avant la prochaine séance : 

- Utilisation du matériel avec ses élèves
- Participation à la recherche (*facultatif et sur inscription*)

## Rencontre du mardi 6 décembre 2022 de 17h30 à 19h10

*Salle : info à venir*

- On fête la St-Nicolas (je dis ça, je dis rien &#x1f385;)
- Bilan des expériences
- Illustration finale de pratiques
- Plan d'action pour la suite (personnel et professionnel)